# Mod Properties
mod_id=thermal_locomotion
mod_name=Thermal Locomotion
mod_version=11.0.1

# Platform Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
java_version=21
mc_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
loader_version_range=[1,)

# Dependency Properties
cofh_core_version=11.0.2
cofh_core_max_version=11.1.0

thermal_core_version=11.0.7
thermal_core_max_version=11.1.0

jei_version=19.21.1.248

# Publishing Properties

# Options: alpha, beta, release
release_type=release
